spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employees-root
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees
          filters:
            - SetPath=/api/v1/employees

        - id: employees-tail
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/employees

        - id: departments-root
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments
          filters:
            - SetPath=/api/v1/departments

        - id: departments-tail
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/departments

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,loggers,gateway
  endpoint:
    gateway:
      enabled: true
