spring:
  mvc:
    problemdetails:
      enabled: true

server:
  error:
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,loggers

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
