spring:
  application:
    name: department-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pppp
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: department
      open-in-view: false
  flyway:
    enabled: true
    locations: classpath:/db/migration
    schemas: department
    default-schema: department
    table: flyway_schema_history_departments
    create-schemas: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-migration-naming: true

server:
  port: 8082

logging:
  level:
    com.example.department: INFO
