spring:
  application:
    name: DEPARTMENT-SERVICE

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,loggers

---
# Enable Config Server import for all profiles EXCEPT 'test'
spring:
  config:
    activate:
      on-profile: "!test"
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true
